---
- name: Install firewalld
  yum:
    name: firewalld
    state: latest

- name: Start the firewall
  service:
     name: firewalld
     enabled: true
     state: started
    
- name: Open the port for http
  firewalld:
    service: http
    immediate: true
    permanent: true
    state: enabled
