---
# Start of webmail playbook
- name: create webmail servers
  hosts: webmail
  vars:
    template_files:
      - src: templates/squirrelmail-config.php.j2
        dest: /etc/squirrelmail/config.php
        owner: root
        group: apache
        mode: 0640
      - src: templates/squirrelmail-httpd-conf.j2
        dest: /etc/httpd/conf.d/squirrelmail.conf
        owner: root
        group: root
        mode: 0644

  tasks:
    - name: Install Squirrelmail
      unarchive: src=http://materials.example.com/squirrelmail-webmail.tar.gz dest=/var/www/html/ copy=no

    - name: Install Apache
      yum:
        name: "{{ item }}"
      with_items:
        - httpd
      notify:
        - Restart httpd

    - name: Create Squirrelmail config. directory
      file: path=/etc/squirrelmail state=directory

    - name: Template out required configuration files
      template:
        src:   "{{ item.src }}"
        dest:  "{{ item.dest }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode:  "{{ item.mode }}"
      with_items: "{{ template_files }}"
      notify:
        - Restart httpd
    - name: Enable and start the web server
      service:
        name: httpd
        state: started
        enabled: yes

  handlers:
    - name: Restart httpd
      service:
        name: httpd
        state: restarted

# End of webmail playbook

# Start of mailserver playbook
- name: Create mailservers
  hosts: mailservers
  tasks:
    - name: Install required packages
      yum:
        name: postfix
        state: installed
      notify:
        - Restart Postfix

    - name: Tempplate main.conf
      template:
        src: templates/main.cf.j2
        dest: /etc/postfix/main.cf
        owner: root
        group: root
        mode: 0644
      notify:
        - Restart Postfix
    - name: Start and enable Postfix
      service:
        name: postfix
        state: started
        enabled: True
...
