- name: Update apache
  hosts: webservers

  tasks:
    - name: Latest version of apache installed
      yum:
        name: httpd
        state: latest
      notify:
        - Restart apache
    - name:
      command: sleep 10

  handlers:
    - name: Restart apache
      service:
        name: httpd
        enabled: yes
        state: restarted
