- name: intranet services for development
  hosts: all
  become: yes
  become_user: root
  tasks:
  - name: latest httpd version installed
    yum:
      name: httpd
      state: latest
  - name: latest firewalld version installed
    yum:
      name: firewalld
      state: latest
  - name: httpd enabled and started
    service:
      name: httpd
      enabled: true
      state: started
  - name: firewalld enabled and started
    service:
      name: firewalld
      enabled: true
      state: started
  - name: firewalld permits http service
    firewalld:
      service: http
      permanent: true
      state: enabled
    notify:
      - restart firewalld
  - name: create .ssh directory
    file:
      path: /root/.ssh
      state: directory
      mode: 0700
  - name: install private key file
    copy:
      src: /root/.ssh/id_rsa
      dest: /root/.ssh/id_rsa
      mode: 0600
  - name: install git configuration
    copy:
      src: /root/.gitconfig
      dest: /root/.gitconfig
      mode: 0644
  - name: get source
    git:
      repo: ssh://student@workstation/var/git/webapp.git
      dest: /var/www/html
      accept_hostkey: yes
  handlers:
    - name: restart firewalld
      service:
        name: firewalld
        state: restarted
