Vagrant.require_version ">= 1.7.0"

Vagrant.configure(2) do |config|

  # Identify which Vagrant box to use
  config.vm.box = "rhel7.1"
  config.vm.box_url = "http://content.example.com/ansible2.3/x86_64/dvd/vagrant/rhel-server-libvirt-7.1-1.x86_64.box"

  # Define host settings
  config.vm.hostname = "dev.lab.example.com"

  # Define sync folder(s)

  # Define shell provisioner

  # Define ansible provisioner

end
