# main.yml
# Steve Bonneville <sbonnevi@redhat.com>
# 2017-Feb-16
#
# Configures standard Git repository using SSH.

    - name: Packages for Git server up to date
      package:
        name: "{{ item }}"
        state: latest
      with_items: "{{ git_packages }}"

    - name: git-shell is in /etc/shells
      lineinfile:
        dest: /etc/shells
        line: /usr/bin/git-shell

    - name: git user exists and uses git-shell
      user:
        name: git
        comment: "Git server"
        shell: /usr/bin/git-shell

    - name: SSH authorized_keys up to date
      authorized_key:
        user: git
        state: present
        key: "{{ item }}"
      with_file: "{{ git_authorized_keys }}"
      when: git_authorized_keys is defined

    # If the directory exists, we don't want to blow away its
    # contents, because it's probably got valid repo data in it!

    - name: Check Git project directory for existence
      stat:
        path: /home/git/{{ git_project }}.git
      register: p

    # If the directory exists, we don't want to blow away its
    # contents, because it's probably got valid repo data in it!

    - name: Create empty {{ git_project }}.git bare repository if missing
      command: git init --bare /home/git/{{ git_project }}.git
      when: not (p.stat.isdir is defined and p.stat.isdir)

    - name: Ensure {{ git_project }}.git owned by git
      file:
        path: /home/git/{{ git_project }}.git
        owner: git
        group: git
        recurse: yes
        state: directory

