---
- name: Set password in inventory file
  replace:
    dest: /root/ansible-tower-setup-bundle-{{ tower_version }}/inventory
    regexp: "password=''"
    replace: "password='redhat'"
    backup: yes
  tags:
    - setpassword
